apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "softhsm-server-chart.fullname" . }}-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
