apiVersion: v1
kind: Secret
metadata:
  name: {{ include "softhsm-server-chart.fullname" . }}-secret
type: Opaque
data:
  pkcs11_proxy_psk: {{ .Values.secret.pkcs11_proxy_psk | b64enc | quote }}
  token_import_test_data: {{ .Values.secret.token_import_test_data | b64enc | quote }}
  token_so_pin: {{ .Values.secret.token_so_pin | b64enc | quote }}
  token_user_pin: {{ .Values.secret.token_user_pin | b64enc | quote }} 
