apiVersion: v1
kind: Service
metadata:
  name: {{ include "softhsm-server-chart.fullname" . }}
spec:
  selector:
    app: {{ include "softhsm-server-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2345
  type: {{ .Values.service.type }}
